### ISSUE TITLE
GuitarMidi-LV2 wont compile. Missing alsa/asoundlib.h

### ISSUE THREAD

**Issue by BeFrankly** [geraldmwangi/GuitarMidi-LV2#1]
Hello,

I just tried to build but some sources seem to be missing. Which alsa source files do I have to install and how to, to get this fixed. And can I run the build on the same folder again. Does build clean up first?

Here is the last output of the build (the german sentence "Datei oder Verzeichnis nicht gefunden" means "File or Folder not found")

 68%] Building CXX object AnalysisApp/CMakeFiles/GuitarMidiAnalysisApp.dir/JuceLibraryCode/include_juce_audio_devices.cpp.o
In file included from /home/frank/Compile/GuitarMidi-LV2/GuitarMidi-LV2/AnalysisApp/JuceLibraryCode/include_juce_audio_devices.cpp:9:
/home/frank/Compile/GuitarMidi-LV2/GuitarMidi-LV2/AnalysisApp/JuceLibraryCode/modules/juce_audio_devices/juce_audio_devices.cpp:151:12: fatal error: alsa/asoundlib.h: Datei oder Verzeichnis nicht gefunden
  151 |   #include <alsa/asoundlib.h>
      |            ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [AnalysisApp/CMakeFiles/GuitarMidiAnalysisApp.dir/build.make:219: AnalysisApp/CMakeFiles/GuitarMidiAnalysisApp.dir/JuceLibraryCode/include_juce_audio_devices.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:172: AnalysisApp/CMakeFiles/GuitarMidiAnalysisApp.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

Regards
Frank

**Comment by BeFrankly** [comment]
Ok, after a little search I found out to install libasound-dev (sudo apt-get install libasound-dev) but now build fails because of missing X11/extensions/Xrandr.h
Error:
/home/frank/Compile/GuitarMidi-LV2/GuitarMidi-LV2/AnalysisApp/JuceLibraryCode/modules/juce_gui_basics/juce_gui_basics.h:334:13: fatal error: X11/extensions/Xrandr.h: Datei oder Verzeichnis nicht gefunden
So please tell us the dependencies and which header files need to be installed. Otherwise you will not get any test results.
Regards
Frank

**Comment by geraldmwangi** [comment]
I pushed an update to master branch, in which the devtools (AnalysisApp) are deactivated by default. Can wipe your build dir and trigger a new build?

**Comment by geraldmwangi** [comment]
one should only need  cmake, lv2-dev, libaubio-dev.

**Comment by geraldmwangi** [comment]
which distro do you run

**Comment by geraldmwangi** [comment]
In case It dosn't work install the libs: freetype2, alsa, libcurl, webkit2gtk-4.0, gtk+-x11-3.0 and their dev packages

**Comment by BeFrankly** [comment]
> which distro do you run
istributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

**Comment by BeFrankly** [comment]
Dear @geraldmwangi ,
I removed the whole dir, did a fresh git clone and started the build procedure again. Now build process and "build install" worked. I will now test it with carla.

**Comment by geraldmwangi** [comment]
Cool. It currently only works till the 5th fret and you have push the input gain very high.It still is not production ready. Have fun , looking forward to your feedback

**Comment by BeFrankly** [comment]
@geraldmwangi , I think you should close this issue, because the main problem in compiling is fixed. I will file another issue that will tell, what I found out by using Guitar-MIDI

**Comment by geraldmwangi** [comment]
Hi. Which distro are you using?

Am 18. Juli 2022 23:20:21 MESZ schrieb Frank ***@***.***>:

**Comment by geraldmwangi** [comment]
I use Ubuntu 20.04

Am 11. Oktober 2022 09:08:27 MESZ schrieb geraldmwangi ***@***.***>:

**Comment by BeFrankly** [comment]
Dear @geraldmwangi ,
at the time of my first post I was using Ubuntu 20.04. Now I'm on 22.04.
